modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/thimblebird/client-profiles/issues"

[[mods]]
modId="clientprofiles"
version="${file.jarVersion}"
displayName="Client Profiles"
#updateJSONURL="https://change.me.example.invalid/updates.json" # https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
displayURL="https://www.curseforge.com/minecraft/mc-mods/client-profiles"
logoFile="clientprofiles.png"
authors="thimblebird"
displayTest="IGNORE_ALL_VERSION"
description='''
Swap out the whole config folder and its contents using commands.

/clientprofile *
'''

[[dependencies.clientprofiles]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.clientprofiles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="CLIENT"
